SortableServiceEntityRepository: inherit from EntityRepository instead of SortableServiceEntityRepository
This fixes the psalm error:
ERROR: MethodSignatureMismatch - src/Repository/ContentNodeRepository.php:19:5 - Method Gedmo\Sortable\Entity\Repository\SortableRepository::__construct is declared final and cannot be overridden (see https://psalm.dev/042)
    public function __construct(EntityManagerInterface $em, string $entityClass = ContentNode::class) {

Because SortableRepository is now marked as final in gedmo/doctrine-extensions v3.11.0.
Instead call the constructor of SortableRepository in SortableServiceEntityRepository.