api/contentNode: add required psalm template parameters
This fixes the following psalm errors:
ERROR: MissingTemplateParam - src/Repository/ContentNodeRepository.php:19:7 - App\Repository\ContentNodeRepository has missing template params when extending App\Repository\SortableServiceEntityRepository, expecting 1 (see https://psalm.dev/182)
class ContentNodeRepository extends SortableServiceEntityRepository implements CanFilterByUserInterface {

ERROR: MissingTemplateParam - src/Repository/ColumnLayoutRepository.php:14:7 - App\Repository\ColumnLayoutRepository has missing template params when extending App\Repository\ContentNodeRepository, expecting 1 (see https://psalm.dev/182)
class ColumnLayoutRepository extends ContentNodeRepository {

ERROR: MissingTemplateParam - src/Repository/MaterialNodeRepository.php:14:7 - App\Repository\MaterialNodeRepository has missing template params when extending App\Repository\ContentNodeRepository, expecting 1 (see https://psalm.dev/182)
class MaterialNodeRepository extends ContentNodeRepository {

ERROR: MissingTemplateParam - src/Repository/MultiSelectRepository.php:14:7 - App\Repository\MultiSelectRepository has missing template params when extending App\Repository\ContentNodeRepository, expecting 1 (see https://psalm.dev/182)
class MultiSelectRepository extends ContentNodeRepository {

ERROR: MissingTemplateParam - src/Repository/SingleTextRepository.php:14:7 - App\Repository\SingleTextRepository has missing template params when extending App\Repository\ContentNodeRepository, expecting 1 (see https://psalm.dev/182)
class SingleTextRepository extends ContentNodeRepository {

ERROR: MissingTemplateParam - src/Repository/StoryboardRepository.php:14:7 - App\Repository\StoryboardRepository has missing template params when extending App\Repository\ContentNodeRepository, expecting 1 (see https://psalm.dev/182)
class StoryboardRepository extends ContentNodeRepository {