api/ResetPasswordProvider: add missing @template-implements
ERROR: MissingTemplateParam - src/State/ResetPasswordProvider.php:12:40 - App\State\ResetPasswordProvider has missing template params when extending ApiPlatform\State\ProviderInterface, expecting 1 (see https://psalm.dev/182)
class ResetPasswordProvider implements ProviderInterface {