print: replace createIncognitoBrowserContext with createBrowserContext
Else we have the error:
ERROR  browser.createIncognitoBrowserContext is not a function
 at Object.handler (server/api/pdf.js:51:1)
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 at async node_modules/h3/dist/index.mjs:1962:19
 at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
 at async Server.toNodeHandle (node_modules/h3/dist/index.mjs:2249:7)

Which was changed in
https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v22.0.0
with PR https://github.com/puppeteer/puppeteer/issues/11834

Which seems related to:
https://github.com/puppeteer/puppeteer/issues/2608